
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CC0057:Unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Program.Main(System.String[])")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.AsyncBenchmark.TaskAsyncFromResultAsync~System.Threading.Tasks.Task{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.AsyncBenchmark.TaskAsyncFromResultAsync~System.Threading.Tasks.Task{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.AsyncBenchmark.TaskAsyncFromResultConfigureAwaitAsync~System.Threading.Tasks.Task{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.AsyncBenchmark.TaskAsyncFromResultConfigureAwaitAsync~System.Threading.Tasks.Task{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.AsyncBenchmark.TaskFromResultAsync~System.Threading.Tasks.Task{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.AsyncBenchmark.TaskFromResultAsync~System.Threading.Tasks.Task{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.AsyncBenchmark.ValueTaskAsyncFromResultAsync~System.Threading.Tasks.ValueTask{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.AsyncBenchmark.ValueTaskAsyncFromResultAsync~System.Threading.Tasks.ValueTask{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.AsyncBenchmark.ValueTaskAsyncFromResultConfigureAwaitAsync~System.Threading.Tasks.ValueTask{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.AsyncBenchmark.ValueTaskAsyncFromResultConfigureAwaitAsync~System.Threading.Tasks.ValueTask{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.AsyncBenchmark.ValueTaskFromResult~System.Threading.Tasks.ValueTask{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.AsyncBenchmark.ValueTaskFromResult~System.Threading.Tasks.ValueTask{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.ValueOrNotBenchmark.AsyncAwaitableTaskAsync~System.Threading.Tasks.Task{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.ValueOrNotBenchmark.AsyncAwaitableTaskAsync~System.Threading.Tasks.Task{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.ValueOrNotBenchmark.AsyncAwaitableValueTaskAsync~System.Threading.Tasks.ValueTask{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.ValueOrNotBenchmark.AsyncAwaitableValueTaskAsync~System.Threading.Tasks.ValueTask{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.ValueOrNotBenchmark.SyncAwaitableTaskAsync~System.Threading.Tasks.Task{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.ValueOrNotBenchmark.SyncAwaitableTaskAsync~System.Threading.Tasks.Task{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.ValueOrNotBenchmark.SyncAwaitableValueTaskAsync~System.Threading.Tasks.ValueTask{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.ValueOrNotBenchmark.SyncAwaitableValueTaskAsync~System.Threading.Tasks.ValueTask{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.ValueOrNotBenchmark.TaskFromResultAsync~System.Threading.Tasks.Task{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.ValueOrNotBenchmark.TaskFromResultAsync~System.Threading.Tasks.Task{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.ValueOrNotBenchmark.ValueTaskFromResult~System.Threading.Tasks.ValueTask{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.ValueOrNotBenchmark.ValueTaskFromResult~System.Threading.Tasks.ValueTask{System.Int32}")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Readability", "RCS1018:Add default access modifier.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Program.Main(System.String[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Readability", "RCS1018:Add default access modifier.", Justification = "<Pending>", Scope = "type", Target = "~T:Bnaya.Samples.Program")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancy", "RCS1163:Unused parameter.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Program.Main(System.String[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("ConfigureAwait", "ConfigureAwaitEnforcer:ConfigureAwaitEnforcer", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.AsyncBenchmark.TaskAsyncFromResult~System.Threading.Tasks.Task{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("ConfigureAwait", "ConfigureAwaitEnforcer:ConfigureAwaitEnforcer", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.AsyncBenchmark.ValueTaskAsyncFromResult~System.Threading.Tasks.ValueTask{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("ConfigureAwait", "ConfigureAwaitEnforcer:ConfigureAwaitEnforcer", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.ValueOrNotBenchmark.AsyncAwaitableTask~System.Threading.Tasks.Task{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("ConfigureAwait", "ConfigureAwaitEnforcer:ConfigureAwaitEnforcer", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.ValueOrNotBenchmark.AsyncAwaitableValueTask~System.Threading.Tasks.ValueTask{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("ConfigureAwait", "ConfigureAwaitEnforcer:ConfigureAwaitEnforcer", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.ValueOrNotBenchmark.SyncAwaitableTask~System.Threading.Tasks.Task{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("ConfigureAwait", "ConfigureAwaitEnforcer:ConfigureAwaitEnforcer", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.ValueOrNotBenchmark.SyncAwaitableValueTask~System.Threading.Tasks.ValueTask{System.Int32}")]