
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Readability", "RCS1018:Add default access modifier.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Program.Main(System.String[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "RCS1102:Make class static.", Justification = "<Pending>", Scope = "type", Target = "~T:Bnaya.Samples.Program")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Readability", "RCS1018:Add default access modifier.", Justification = "<Pending>", Scope = "type", Target = "~T:Bnaya.Samples.Program")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "RCS1165:Unconstrained type parameter checked for null.", Justification = "<Pending>", Scope = "member", Target = "~M:System.Threading.Tasks.LightTask`1.GetHashCode~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "RCS1165:Unconstrained type parameter checked for null.", Justification = "<Pending>", Scope = "member", Target = "~M:System.Threading.Tasks.LightTask`1.ToString~System.String")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancies in Symbol Declarations", "RECS0154:Parameter is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Program.Main(System.String[])")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CC0057:Unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Program.Main(System.String[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Logic.LTapFashion(System.Func{System.Threading.Tasks.LightTask{System.String}},System.String)~System.Threading.Tasks.LightTask{System.Object}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Logic.OldFashion(System.Func{System.String},System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Logic.TapFashion(System.Func{System.Threading.Tasks.Task{System.String}},System.String)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Logic.VTapFashion(System.Func{System.Threading.Tasks.ValueTask{System.String}},System.String)~System.Threading.Tasks.ValueTask{System.Object}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Program.ExecValueAsync~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Program.GetContentAsync~System.Threading.Tasks.Task{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Program.GetValueContentAsync~System.Threading.Tasks.ValueTask{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Program.Main(System.String[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Logic.LTapFashionAsync(System.Func{System.Threading.Tasks.LightTask{System.String}},System.String)~System.Threading.Tasks.LightTask{System.Object}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Logic.TapFashionAsync(System.Func{System.Threading.Tasks.Task{System.String}},System.String)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Logic.VTapFashionAsync(System.Func{System.Threading.Tasks.ValueTask{System.String}},System.String)~System.Threading.Tasks.ValueTask{System.Object}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Logic.LTapFashionAsync(System.Func{System.Threading.Tasks.LightTask{System.String}},System.String)~System.Threading.Tasks.LightTask{System.Object}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Logic.LTapFashionAsync(System.Func{System.Threading.Tasks.LightTask{System.String}},System.String)~System.Threading.Tasks.LightTask{System.Object}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Logic.OldFashion(System.Func{System.String},System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Logic.OldFashion(System.Func{System.String},System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Logic.TapFashionAsync(System.Func{System.Threading.Tasks.Task{System.String}},System.String)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Logic.TapFashionAsync(System.Func{System.Threading.Tasks.Task{System.String}},System.String)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Logic.VTapFashionAsync(System.Func{System.Threading.Tasks.ValueTask{System.String}},System.String)~System.Threading.Tasks.ValueTask{System.Object}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Logic.VTapFashionAsync(System.Func{System.Threading.Tasks.ValueTask{System.String}},System.String)~System.Threading.Tasks.ValueTask{System.Object}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancy", "RCS1213:Remove unused member declaration.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Program.ExeAcyncAsync~System.Threading.Tasks.ValueTask{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancy", "RCS1163:Unused parameter.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Program.Main(System.String[])")]