
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Controllers.ImageManipController.GetBytesWithFilterAsync(System.Int32,System.String,SkiaSharp.SKImageFilter,SkiaSharp.SKColorFilter,SkiaSharp.SKShader,SkiaSharp.SKBlendMode)~System.Threading.Tasks.ValueTask{System.Byte[]}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Controllers.ImageManipController.GetMergeAsync(System.Int32,System.String)~System.Threading.Tasks.ValueTask{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Controllers.ImageManipController.GetWithFilterAsync(System.Int32,System.String,SkiaSharp.SKImageFilter,SkiaSharp.SKColorFilter,SkiaSharp.SKShader,SkiaSharp.SKBlendMode)~System.Threading.Tasks.ValueTask{Microsoft.AspNetCore.Mvc.IActionResult}")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Controllers.ImageManipController.GetBytesWithFilterAsync(System.Int32,System.String,SkiaSharp.SKImageFilter,SkiaSharp.SKColorFilter,SkiaSharp.SKShader,SkiaSharp.SKBlendMode)~System.Threading.Tasks.ValueTask{System.Byte[]}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Controllers.ImageManipController.GetBytesWithFilterAsync(System.Int32,System.String,SkiaSharp.SKImageFilter,SkiaSharp.SKColorFilter,SkiaSharp.SKShader,SkiaSharp.SKBlendMode)~System.Threading.Tasks.ValueTask{System.Byte[]}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Startup.Configure(Microsoft.AspNetCore.Builder.IApplicationBuilder,Microsoft.AspNetCore.Hosting.IHostingEnvironment)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Startup.Configure(Microsoft.AspNetCore.Builder.IApplicationBuilder,Microsoft.AspNetCore.Hosting.IHostingEnvironment)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Startup.ConfigureServices(Microsoft.Extensions.DependencyInjection.IServiceCollection)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Startup.ConfigureServices(Microsoft.Extensions.DependencyInjection.IServiceCollection)")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0105:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Controllers.ImageManipController.GetGrayscaleAsync(System.Int32,System.String,System.Single)~System.Threading.Tasks.ValueTask{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0105:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Controllers.ImageManipController.GetRotateAsync(System.Int32,System.String,System.Int32)~System.Threading.Tasks.ValueTask{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0105:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Controllers.ImageManipController.GetShaderAsync(System.Int32,System.String)~System.Threading.Tasks.ValueTask{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("ConfigureAwait", "ConfigureAwaitEnforcer:ConfigureAwaitEnforcer", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Controllers.ImageManipController.GetBytesWithFilterAsync(System.Int32,System.String,SkiaSharp.SKImageFilter,SkiaSharp.SKColorFilter,SkiaSharp.SKShader,SkiaSharp.SKBlendMode)~System.Threading.Tasks.ValueTask{System.Byte[]}")]